print('This is Jobaer')
print('lets start python programming language')
print('Jobaer---Banna')
print('Jobaer','Banna')
print('Jobaer','Banna',sep='*****')
print('I','am','from','Bangladesh',sep='$$$$')